services:
  front-end:
    container_name: front-end
    image: ghcr.io/k10app/frontend
    restart: always
    ports:
      - "80:80"
    links:
      - catalog
      - bus
    depends_on:
      - catalog
      - bus
  catalog:
    container_name: catalog
    image: ghcr.io/k10app/catalog
    restart: always
    volumes:
      - C:\k10app\:/catalog/certificates
    ports:
      - "3001:80"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - MONGODB_HOST=mongo
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
  mongo:
    container_name: mongo
    restart: always
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - C:\k10app\mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
  bus:
    container_name: bus
    restart: always
    image: ghcr.io/k10app/basicuserservice
    volumes:
      - C:\k10app:/basicuserservice/certificates
    environment:
      - MARIADB_HOST=192.168.0.8
      - name=bus
    ports:
      - "3002:80"
    links:
      - maria
    depends_on:
      - maria
  maria:
    container_name: maria
    restart: always
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - C:\k10app\basicUser:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=userdb
      - MARIADB_USER=userdblogin
      - MARIADB_PASSWORD=userdbpassword
      - MARIADB_ROOT_PASSWORD=userdbrootpass
  orders:
    container_name: orders
    restart: always
    image: ghcr.io/k10app/order
    ports:
      - "3003:80"
    volumes:
      - C:\k10app:/order/certificates
    environment:
      - POSTGRES_HOST=postgres
      - CATALOG_SERVER=catalog
    links:
      - catalog
      - postgres
    depends_on:
      - catalog
      - postgres
  postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - C:\k10app\postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=order
      - POSTGRES_USER=orderlogin
      - POSTGRES_PASSWORD=orderpassword
